<a href="https://colab.research.google.com/github/srihithareddy749/aiml/blob/main/assignment%20(1)%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
print("LISTS")
a = [1, 2, 3, 4, 5]
print(a)
print("ARRAYS")
array1=np.array([6,17,8,29,5])
array2=np.array([1,2,23,4,45])
print(array1)
print(array2)
print("DATA TYPES")
print(type(array1))
print(type(array2))
print("MULTIPLICATION AND DIVISION OF ARRAYS")
mult_array = array1 * array2
print("Multiplication of arrays:", mult_array)
div_array = array2 / array1
print("Division of arrays:", div_array)
power_array = np.power(array1, 2)
print("Power of array1 elements:", power_array)
print("ADDITION OF ARRAYS")
add=array1+array2
print(add)
print("IMPLEMENTATIONS")

exp_array1 = np.exp(array1)
print("Exponential of array1:", exp_array1)

sin_array1 = np.sin(array1)
print("Sine of array1:", sin_array1)
print("LOG()")
result = np.log(array1)
print(result)
print("LOG2")
print(np.log2(array1))

LISTS
[1, 2, 3, 4, 5]
ARRAYS
[ 6 17  8 29  5]
[ 1  2 23  4 45]
DATA TYPES
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
MULTIPLICATION AND DIVISION OF ARRAYS
Multiplication of arrays: [  6  34 184 116 225]
Division of arrays: [0.16666667 0.11764706 2.875      0.13793103 9.        ]
Power of array1 elements: [ 36 289  64 841  25]
ADDITION OF ARRAYS
[ 7 19 31 33 50]
IMPLEMENTATIONS
Exponential of array1: [4.03428793e+02 2.41549528e+07 2.98095799e+03 3.93133430e+12
 1.48413159e+02]
Sine of array1: [-0.2794155  -0.96139749  0.98935825 -0.66363388 -0.95892427]
LOG()
[1.79175947 2.83321334 2.07944154 3.36729583 1.60943791]
LOG2
[2.5849625  4.08746284 3.         4.857981   2.32192809]
